social/groups/urls.py
#groups urls.py

from django.urls import path
from . import views

app_name = 'group'


urlpatterns = [
    path('', views.ListGroup.as_view(),name='all'),
    path('new/', views.CreateGroup.as_view(),name='create'),
    path('post/<slug>/',views.SingleGroup.as_view() ,name='single')
    path('join/<slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug>/', views.LeaveGroup.as_view(), name='leave'),

]

social/posts/urls.py
#POST URLS.PY
from django.urls import path
from . import views

app_name = 'posts' # refence when using relative url

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/', views.UserPost.as_view(), name='for_user'),
    path('by/<username>/<int:pk>',views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),

]

social/social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    #connecting to accounts urls.py
    path('accounts/', include('django.contrib.auth.urls')),
    #connecting to the onboard auth urls.py for the login, Logout Views and further
    # authorization
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks', views.thanksPage.as_view(), name='thanks'),
]

social/groups/models.py
from django.db import models

#GROUPS/MODELS.PY file

from django.utils.text import slugify
 # package - slugify, it allows to remove any characters that arent alpha numeric.
 # use case - if user input a string with white spaces, this import allows the user
 #            to work with this string by convering the white space into dashes.

 import misaka
 # https://misaka.61924.nl/
 # allows the use of markdown inside of the post.

from django.contrib.auth import get_user_model
User = get_user_model()
# get the the model of active user then be using their model information latet


from django import template
register = template.Library()
#this will be used later on the development
# will need to create other functionality to fully describe

# Create your models here#
class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    #name of the group, only allowing it to be unique no overlapping names
    slug = models.SlugField(allow_unicode=True, unique=True)
    #the slug field, must be unique so that group name and slugs dont overlap each other
    description = models.TextField(blank=True, default='')
    # group description attribute, description of group must not be blank
    description_html = models.TextField(editable=False, default='', blank='True')
    #description_html - if we want the html version of the description, also cant be black
    # could be used later.
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        #save method, before saving there are some formatting that needs to
        # to be processed to be saved properly

        self.slug = slugify(self.name)
        # this is where slugify come into play, replaces values to be able to be saved
        self.description_html = misaka.html(self.description)
        # this is where misaka comes into play, allows markdown in the description
        super().save(*arg, **kwargs)


        def get_absolute_url(self):
            return reversed('groups:single', kwargs={'slug':self.slug})

        class Meta:
            ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    # the member is related to the group class through the ForeignKey
    # whoich we called memberships

    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)
    #This takes the user that was stated earlier to the script, the current active
    # use. then we get that user and link them to the various groups they belong to and/or
    # have them a member of.

    def __str__(self):
        # return username attribute instead of a whole object
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

social/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.urls import reverse
from django.views import generic
from .models import Group, groupMember

from django.shortcuts import get_object_or_404
from django.contrib import messages
# Create your views here.

class CreateGroup(LoginRequiredMixin, generic.CreateView)
# The view that allows the user to create a forum.
    fields('name', 'description')
    # the fields from the model we want to the user to edit
    model = Group
    # DB connection with group DB/Model
    #NOTE STILL NEED TO CONNECT TO TEMPLATE

class SingleGroup(generic.DetailView):
# the view to see all the post in a group
    model = Group

class ListGroup(generic.ListView):
# the View that allows the user to see ALL the available form look into
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):
    #this is the view that enables the users to join the group
    # this will contain validation as you can not join a group twice.
    def get_redirect_url(self, *args, **kwargs):
        return reverse('group:single', kwargs={'slug':self.kwargs.get('slug')})
        #sends the users to the detail view of the group they want to join,
        # to know which group it is we get the slug pk on the current group being click
        # and match it with the same pk within the groups model.

    def get(self, request, *args, **kwargs):
        # try to get a group this person is looking at or return a 404 page
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))
        try:
            GroupMemer.objects.create(user=self.request.user, group=group)
            # try to get a group member object where the user is equal to the current user and the group is equalto group
        except IntegrityError:
            messages.warning(self.request,('WARNING! Already a member'))
        else:
            messages.success(self.request,'You are now a member')
        return super().get(request, *args, **kwargs)

class LeaveGroup(LoginRequiredMixin, generic.RedirectView):
# description: this view enables the user to leave a group if they are currently
# in one. once a person leave a leavegroup funtion view send the user back to the
# detail view of group they just left. also there is a get function that...
# if they try to leave the group it check that user are a meber of selected the group
# and if sends an error to the user that -they are not in the group they are leaving.
# else, if they are in the member list of the group you can delete them and send a success
# message.
    pass
    def get_redirect_url(self, *args, **kwargs):
    #the leave group view is exactly the same with JoinGroup View, where if the
    # user leves the group it send them to the froup detail page
        return reverse('group:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        # the validation method that prevents the user from leaving a group if
        # they're not already in the current one they want to leave
        try:
        # try to create a membership object that gets the model infromation
        # from the GroupMember model, more specifically(filter) the current user
        # current group slug. tooo
            membership = models.GroupMember.objects.filter(
            user=self.request.user,
            group__slug=self.kwargs.get('slug')
            )
        except models.GroupMember.DoesNotExist:
            # if the member is not a member of the group
            messages.warning(self.request,'Sorry you are not in this group!')
        else:
            membership.delete()
            messages.success(self.request, 'You have successfully left the group!')
        return super().get(request, *args, **kwargs)

social/groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      <!-- these block tag wiil be used to inherit to all the other templates
          in the groups template folder, these different tag will be allow
          to layout the unique content distinct to the webpage -->
      {% block pregroup %}

      {% endblock %}

      {% block group_content %}

      {% endblock %}

      {% block postgroup %}

      {% endblock %}


    </div>

  </div>


{%endblock%}

social/groups/templates/groups/group_detail.html
{% extends from 'group/group_base.html' %}

{% block pregroup %}
<!-- before the group show the current group information - linked and found in
group model -  whoch is linked to the class based views -->
<h1>{{group.name}}</h1>
<h2>member count: {{group.members.count}}</h2>
<!-- give option to leave or join the group button, if the user is a loged in
and if the user is a member or not -->

<div class="content">
  {% if user in group.members.all %}
  <!-- if the user in the group's member list(attribute of group model) -->
  <a href="{%url 'groups:leave' slug=group.slug %}"
  class='btn btn-lg btn-fill btn-warning'>Leave Group</a>
  <!-- page not done however, will be done in the urls.py -->
  {% else %}
  <a href="{%url 'groups:join' slug=group.slug %}"
  class='btn btn-lg btn-fill btn-primary'>Join Group</a>
  <!-- page not done however, will be done in the urls.py -->
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
  {% if group.post.count == 0 %}
   <!--checks if the current froup contains post
 if there is NO post then show message -->
   <h2>No Post in this group yet</h2>
   {%else %}
   <!-- if there is a post, cycle through all the post linked with the current gorup
 and list them out -->
   {% for p in group.posts %}
    {% include "posts/_post.html" %}
    <!-- while listing the post, per post being iterated the template call -include,
     injects very common post html code. enabling to practice DRY principle-->
   {% endfor %}
  {% endif %}
</div>

social/groups/templates/groups/group_form.html
{% extends 'group/group_base.html' %}
{% load bootstrap3 %}
<!-- its a form so we load bootstrap to aid the development -->
{%block group_content %}
  <h4>create form</h4>
  <form action="{url 'group:create'}" method="POST" id='groupForm'>
    <!-- once user submit send to create page -->
    {% csrf_token %}
    {% bootstrap_form form %}
    <!-- inject the form (which is connected from the CreateView)-->
    <input type="submit" class="btn btn-primary btn-large" value="Create">
  </form>
{% endblock %}

social/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
  <div class="col-md-4">
    <div class="content">
      <!-- if the user logged in and authenticated
      show a message saying welcome back with a link to the user's
      profile(containing all thier post), display the current users username-->
      {% if user.is_authenticated %}
      <h2>Welcome back!</h2>
      <a href="{%url 'posts:for_user' username=user.username %}">
        @{{user.username}}
      </a>
      <!-- if not  -->
      {% endif %}
      <h2>Groups</h2>
      <p>Welcome to the Groups page! </p>
    </div>
    <!-- if the user is authenticated, give option to create a new group -->
    {% user.is_authenticated %}
      <a href="{%url 'group:create'%}" class='btn btn=md btn-fil btn-warning'>
        Create new Group
      </a>
    {%endif%}
  </div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
  <div class="lsit-group">
    {% for group in object_list %}
    <!-- object list - this is the list of groups object within group.html   -->
    <a class ='list-group-item' href="{%url 'group:single' slug=group.slug %}">
      <h3 class='title list-group-item-heading'>{{group.name}}</h3>
        <!-- have an ancher tag to link to the group name through the slug connection -->
        <div class="list-group-item container-fluid">
          {{group.description|safe}}
          <!-- get the description attribute of the group model and '|safe',
          allows the use of html code in safe way e.g if something is bold, you
          see the format instead of seeing the tag -->
          <div class="row">
            <!-- the follwoing themeplate tag, is the method of
              showing how many member and post each group object has in the
              list of groups -->
            <div class="col-md-4">
              <span class ='badge'>{{group.members.count}}</span>
              member{{group.members.count|pluralized}}
            </div>
            <div class="col-md-4">
              <span class='badge'>{{group.post.count}}</span>
              post{{group.post.count|pluralized}}
            </div>
          </div>
        </div>
    </a>
    {% endfor %}
  </div>
</div>
{% endblock %}