social/groups/urls.py
#groups urls.py

from django.urls import path
from . import views

app_name = 'group'


urlpatterns = [
    path('', views.ListGroup.as_view(),name='all'),
    path('new/', views.CreateGroup.as_view(),name='create'),
    path('post/<slug>/',views.SingleGroup.as_view() ,name='single')
    path('join/<slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug>/', views.LeaveGroup.as_view(), name='leave'),

]

social/posts/urls.py
#POST URLS.PY
from django.urls import path
from . import views

app_name = 'posts' # refence when using relative url

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/', views.UserPost.as_view(), name='for_user'),
    path('by/<username>/<int:pk>',views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),

]

social/social/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    #connecting to accounts urls.py
    path('accounts/', include('django.contrib.auth.urls')),
    #connecting to the onboard auth urls.py for the login, Logout Views and further
    # authorization
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks', views.thanksPage.as_view(), name='thanks'),
]

social/posts/models.py
from django.db import models
#POST/MODELS.PY
from django.urls import reverse
# method to redirect to another page

from django.conf import settings
# allows custom settings.

import misaka
# allow markdown on post

from groups.model import Group
# to make a link a post to a group
# Create your models here.

from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts')
    # link the made post with the auther of the post user model
    created_at = models.DateTimeField(auto_now=True)
    # save the current time its created
    message = models.TextField()
    # messate attribute, the context of the post
    message_html = models.TextField(editable=False)
    # allow markdown on message attribute,
    # users cant directly edit it but grab it directly from message which will be done
    # in the saved function of the model
    group = models.ForeignKey(Group, related_name='posts', null=True, Blank = True)

    def __str__(self):
        return self.message

    def save(self, *args, **kwars):
        self.message_html = misaka.html(self.message)
        # this is where the markdown of the message happens
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        # redirect the user to a template, with the kwargs that will inject the
        # users username, and pk(primary key) a method to relate post to url
        return reverse('posts:single', kwargs={'username':self.user.username,
                                        'pk': self.pk})

    def Meta:
        ordering = ['-created_at'] # DESC post on top
        unique_together = ['user', 'message'] # every message is uniquely linked to a user. 

social/posts/views.py
from django.shortcuts import render
#POST VIEWS.PY
# Create your views here.

# ensure people has to be logged into do some views required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
# used when a user want to delete some post

from django.views import generic

from django.http import Http404
#used for error message

from braces.views import SelectRelatedMixin
# A simple mixin which allows you to specify a list or tuple of foreign
#  key fields to perform a select_related on. - will be display later on

from. import models

from . import forms

from django.contrib.auth import get_user_model
User = get_user_model()
# when someone is logged in a session i can get this User oject and call
# off the current users attributes.


class PostListClass(SelectRelatedMixin, generic.ListView):
#Description:
    # once you select a person you can see the user's post or select a
    # group see the posted post.
    model = models.Post
    select_related = ('user' 'group')
    #selectedRelatedMixin method /attribute that allows us to create a tuple
    # of related models which are foreign keys to the post

class UserPost(generic.ListView):
    model = models.Post
    template_name = 'post/user_post_list.html'

    def get_queryset(self):
        #creating a method of  grabbed item in the list.
        # the first method is going to 'try' to set the post.user/user that belongs
        # to a particular post equal to The current users related post and then
        # get where the username is ecaxtly whatever the user that currently logged in
        # or whatever user it happens to click on. if the user does not exisit raise an error
        # else then return all the post.
        try:
            self.post.user = User.object.prefetch_related('posts').get(username__iexac=self.kwargs.get('usernanme'))
        except user.DoesNotExist:
            raise Http404
        else:
            return self.post_user.post.all()


    def get_context_data(self, **kwargs):
        #dexcription: method of returning the context data object esential connected
        #             to the whoever posted that specific user
        context = super().get_context_data(**kwargs)
        context = ['post_user'] = self.post_user
        return context

class PostDetail(selectedRelatedMixin, generic.DetailView):
    # description: the detail view when you click on a singular post
    models = models.post
    select_related = ('user', 'group')

    def get_queryset(self):
        # get the queryset for the post and filter it by the extaxt username
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwarg.get('username'))

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
# the view that allows the users to create post
    fields = ('message', 'group')
    #the fields we want the users to edit
    model = models.Post

    def form_valid(self, form):
        #to ensure that there is no diplicate when saving the models
        # connect the post.user with the actual user
        self.object = form.save(commit=false)
        self.object.user = self.request.user
        self.obeject.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin, SelectedRelatedMixin, generic.DeleteView):
    # the view that deletes post
    model = models.Post
    select_related = ('user', 'group')

    success_url = reverse_lazy('posts:all')
    # redirect users to another once the deletion of a post is done
    # which is the list of all the post
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Delete')
        return super().delete(*argsm **kwargs)

social/posts/templates/posts/_post.html
<!-- no need to extends to any base.html, crack right in! -->
<div class="post-media">
  <!-- Description:
this is going to display all the current post message then have the authers username
underneeth it the message. also have the username link to another page that,
list out the users post.
  -->
  <h3>{{post.message.html|safe}}</h3>
  <div class="media-body">
    <strong>{{post.user.username}}</strong>
    <h5 class='media-heading'>
      <span class='username'>
        <a href="{% url post:for_user username=post.user,username %}"></a>
      </span>
    <time class='time'>
      <!-- able to show the timedate the post was created at -->
      <a href="{% url 'post:single' username=post.user.username pk=post.pk %}"></a>
    </time>
    </h5>
    <div class="media-footer">
      {# now give the option to delete post #}
      {% if user.is_authenicated and post.user == user %}
      <a href="{% url 'post:delete' pk=post.pk %}" title='delete' class='btn btn-simple'></a>
      {# give a link to the delete post with the post corresponf pk #}
      <span class="fa fa-remove text-danger" aria-hidden="true"></span>
      <span class="text-danger icon-label">Delete</span>
      {% endif %}
    </div>
  </div>

</div>

social/posts/templates/posts/post_base.html
{% extends "base.html" %}
{% block content %}
<div class="posts-page">
  <div class="container">
    <div class="row">
      {% block prepost %} {% endblock %}
      {% block post_content %} {% endblock %}
      {% block post_post %} {% endblock %}


    </div>

  </div>

</div>

social/posts/templates/posts/post_confirm_delete.html
{% extends 'post/post_base.html'%}

{% block post_content %}
<h3>Are you sure you want to delete this post? </h3>

<div class="posts">
  {% include 'post/_post.html' with post=object hide_delete=True %}
  {# show the current post that the user want to delete #}
</div>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger btn-large" value="Confirm Delete">
  {# confirm delete  #}


  <a href="{% url 'post:single' username = user.usrname pk=object.pk %}"
  class= 'btn btn-simple btn-large btn-default'>Cancel</a>
  {# a cancel button to go back to the post #}

</form>

{% endblock %}

social/posts/templates/posts/post_detail.html
{% extends 'post/post_base.html' %}
{% block post_content %}
<div class="col-md-8">

  {%include 'post/_post.html' %}
</div>

{% endblock %}

social/posts/templates/posts/post_form.html
{% extends 'post/post_base.html' %}
{% load bootstrap3 %}
{% block post_content %}

<h4>Create a New post</h4>

<form id="postForm" action="{% url 'post:create' %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="btn btn-primary btn-large" value="Post">

</form>

{% endblock %}

social/posts/templates/posts/post_list.html
{%extends 'post/post_base.html'%}
{% pre_post_content %}
<div class="col-md-4">
  {% if request.user.is_authenicated %}
  <div class="card card-with-shadow">
    <div class="content">
      <h5 class='title'>Your Groups</h5>
      <ul class='list-unstyled'>
        {% for member_group in get_user_groups%}
        <!-- this is form the models.py in teh model app, that it a foriegn key
      all the a link from post to the group memeber - if your user, for every Group
      the user is a member of... -->
      <li clas='group li-with-bullet'>
        <a href="{% url 'group:single' slug=member_group.group.slug %}"></a>
        <!-- grab all the member's join group and the group.slug  -->
      </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  {%end if%}
  <div class="card card-with-shadow">
    <div class="content">
      <h5 class='title'>all Groups</h5>
      <ul class='list-unstyled'>
        <!-- list out all the groups the user is not a member to -->
        {% for other in get_other_groups %}
        <li class="group li-with-bullet">
          <a href="{% url'group:single' slug=other_group.slug %}"></a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
  <!-- injecting all the post  -->
  {% for post in post_list %}
    {% include 'post/_post.html'%}
    <!-- inject a file full of html code file, iteratively  -->
  {% endfor %}
</div>
{% endblock %}

social/posts/templates/posts/user_post_list.html
{% extends 'post/post_base.html' %}
{% block prepost %}
<div class="col-md-4">
  <h1>@{{post_user.username}}</h1>
  <p>Post History</p>
</div>
{% endblock %}

{% block post_content %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include 'post/_post.html'%}
      {% endfor %}
  </div>
{% endblock %]}